CREATE OR REPLACE PACKAGE ruby
IS
  FUNCTION call_s(obj IN VARCHAR2, meth IN VARCHAR2 := NULL, narg IN PLS_INTEGER := NULL,
    a1 IN ANYDATA := NULL, a2 IN ANYDATA := NULL, a3 IN ANYDATA := NULL,
    a4 IN ANYDATA := NULL, a5 IN ANYDATA := NULL, a6 IN ANYDATA := NULL,
    a7 IN ANYDATA := NULL, a8 IN ANYDATA := NULL, a9 IN ANYDATA := NULL,
    a10 IN ANYDATA := NULL, a11 IN ANYDATA := NULL, a12 IN ANYDATA := NULL,
    a13 IN ANYDATA := NULL, a14 IN ANYDATA := NULL, a15 IN ANYDATA := NULL,
    a16 IN ANYDATA := NULL, a17 IN ANYDATA := NULL, a18 IN ANYDATA := NULL,
    a19 IN ANYDATA := NULL, a20 IN ANYDATA := NULL) RETURN VARCHAR2;

  FUNCTION call_n(obj IN VARCHAR2, meth IN VARCHAR2 := NULL, narg IN PLS_INTEGER := NULL,
    a1 IN ANYDATA := NULL, a2 IN ANYDATA := NULL, a3 IN ANYDATA := NULL,
    a4 IN ANYDATA := NULL, a5 IN ANYDATA := NULL, a6 IN ANYDATA := NULL,
    a7 IN ANYDATA := NULL, a8 IN ANYDATA := NULL, a9 IN ANYDATA := NULL,
    a10 IN ANYDATA := NULL, a11 IN ANYDATA := NULL, a12 IN ANYDATA := NULL,
    a13 IN ANYDATA := NULL, a14 IN ANYDATA := NULL, a15 IN ANYDATA := NULL,
    a16 IN ANYDATA := NULL, a17 IN ANYDATA := NULL, a18 IN ANYDATA := NULL,
    a19 IN ANYDATA := NULL, a20 IN ANYDATA := NULL) RETURN NUMBER;

  FUNCTION call_f(obj IN VARCHAR2, meth IN VARCHAR2 := NULL, narg IN PLS_INTEGER := NULL,
    a1 IN ANYDATA := NULL, a2 IN ANYDATA := NULL, a3 IN ANYDATA := NULL,
    a4 IN ANYDATA := NULL, a5 IN ANYDATA := NULL, a6 IN ANYDATA := NULL,
    a7 IN ANYDATA := NULL, a8 IN ANYDATA := NULL, a9 IN ANYDATA := NULL,
    a10 IN ANYDATA := NULL, a11 IN ANYDATA := NULL, a12 IN ANYDATA := NULL,
    a13 IN ANYDATA := NULL, a14 IN ANYDATA := NULL, a15 IN ANYDATA := NULL,
    a16 IN ANYDATA := NULL, a17 IN ANYDATA := NULL, a18 IN ANYDATA := NULL,
    a19 IN ANYDATA := NULL, a20 IN ANYDATA := NULL) RETURN BINARY_DOUBLE;
END;
/

CREATE OR REPLACE PACKAGE BODY ruby
IS
  FUNCTION call0(rettype PLS_INTEGER, obj IN VARCHAR2, meth IN VARCHAR2, narg IN PLS_INTEGER,
    a1 IN ANYDATA, a2 IN ANYDATA, a3 IN ANYDATA,
    a4 IN ANYDATA, a5 IN ANYDATA, a6 IN ANYDATA,
    a7 IN ANYDATA, a8 IN ANYDATA, a9 IN ANYDATA,
    a10 IN ANYDATA, a11 IN ANYDATA, a12 IN ANYDATA,
    a13 IN ANYDATA, a14 IN ANYDATA, a15 IN ANYDATA,
    a16 IN ANYDATA, a17 IN ANYDATA, a18 IN ANYDATA,
    a19 IN ANYDATA, a20 IN ANYDATA) RETURN ANYDATA
  IS LANGUAGE C LIBRARY extproc_ruby_lib NAME "extproc_ruby_impl" WITH CONTEXT
  PARAMETERS
  (CONTEXT, RETURN INDICATOR, rettype, obj, obj INDICATOR, meth, meth INDICATOR, narg, narg INDICATOR,
   a1, a1 INDICATOR, a2, a2 INDICATOR, a3, a3 INDICATOR, a4, a4 INDICATOR, a5, a5 INDICATOR,
   a6, a6 INDICATOR, a7, a7 INDICATOR, a8, a8 INDICATOR, a9, a9 INDICATOR, a10, a10 INDICATOR,
   a11, a11 INDICATOR, a12, a12 INDICATOR, a13, a13 INDICATOR, a14, a14 INDICATOR, a15, a15 INDICATOR,
   a16, a16 INDICATOR, a17, a17 INDICATOR, a18, a18 INDICATOR, a19, a19 INDICATOR, a20, a20 INDICATOR);

  FUNCTION call_s(obj IN VARCHAR2, meth IN VARCHAR2 := NULL, narg IN PLS_INTEGER := NULL,
    a1 IN ANYDATA := NULL, a2 IN ANYDATA := NULL, a3 IN ANYDATA := NULL,
    a4 IN ANYDATA := NULL, a5 IN ANYDATA := NULL, a6 IN ANYDATA := NULL,
    a7 IN ANYDATA := NULL, a8 IN ANYDATA := NULL, a9 IN ANYDATA := NULL,
    a10 IN ANYDATA := NULL, a11 IN ANYDATA := NULL, a12 IN ANYDATA := NULL,
    a13 IN ANYDATA := NULL, a14 IN ANYDATA := NULL, a15 IN ANYDATA := NULL,
    a16 IN ANYDATA := NULL, a17 IN ANYDATA := NULL, a18 IN ANYDATA := NULL,
    a19 IN ANYDATA := NULL, a20 IN ANYDATA := NULL) RETURN VARCHAR2
  IS
    rval ANYDATA;
  BEGIN
    rval := call0(DBMS_TYPES.TYPECODE_VARCHAR2, obj, meth, narg, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20);
    IF rval IS NOT NULL THEN
      RETURN rval.AccessVarchar2();
    ELSE
      RETURN NULL;
    END IF;
  END;

  FUNCTION call_n(obj IN VARCHAR2, meth IN VARCHAR2 := NULL, narg IN PLS_INTEGER := NULL,
    a1 IN ANYDATA := NULL, a2 IN ANYDATA := NULL, a3 IN ANYDATA := NULL,
    a4 IN ANYDATA := NULL, a5 IN ANYDATA := NULL, a6 IN ANYDATA := NULL,
    a7 IN ANYDATA := NULL, a8 IN ANYDATA := NULL, a9 IN ANYDATA := NULL,
    a10 IN ANYDATA := NULL, a11 IN ANYDATA := NULL, a12 IN ANYDATA := NULL,
    a13 IN ANYDATA := NULL, a14 IN ANYDATA := NULL, a15 IN ANYDATA := NULL,
    a16 IN ANYDATA := NULL, a17 IN ANYDATA := NULL, a18 IN ANYDATA := NULL,
    a19 IN ANYDATA := NULL, a20 IN ANYDATA := NULL) RETURN NUMBER
  IS
    rval ANYDATA;
  BEGIN
    rval := call0(DBMS_TYPES.TYPECODE_NUMBER, obj, meth, narg, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20);
    IF rval IS NOT NULL THEN
      RETURN rval.AccessNumber();
    ELSE
      RETURN NULL;
    END IF;
  END;

  FUNCTION call_f(obj IN VARCHAR2, meth IN VARCHAR2 := NULL, narg IN PLS_INTEGER := NULL,
    a1 IN ANYDATA := NULL, a2 IN ANYDATA := NULL, a3 IN ANYDATA := NULL,
    a4 IN ANYDATA := NULL, a5 IN ANYDATA := NULL, a6 IN ANYDATA := NULL,
    a7 IN ANYDATA := NULL, a8 IN ANYDATA := NULL, a9 IN ANYDATA := NULL,
    a10 IN ANYDATA := NULL, a11 IN ANYDATA := NULL, a12 IN ANYDATA := NULL,
    a13 IN ANYDATA := NULL, a14 IN ANYDATA := NULL, a15 IN ANYDATA := NULL,
    a16 IN ANYDATA := NULL, a17 IN ANYDATA := NULL, a18 IN ANYDATA := NULL,
    a19 IN ANYDATA := NULL, a20 IN ANYDATA := NULL) RETURN BINARY_DOUBLE
  IS
    rval ANYDATA;
  BEGIN
    rval := call0(DBMS_TYPES.TYPECODE_BDOUBLE, obj, meth, narg, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20);
    IF rval IS NOT NULL THEN
      RETURN rval.AccessBDouble();
    ELSE
      RETURN NULL;
    END IF;
  END;
END;
/
